# EventListener
services:
    _defaults:
        autowire: true
        autoconfigure: true


    Esit\Getlawclient\Classes\Listener\OnHandleDataListener:
        tags:
            - { name: kernel.event_listener, event: Esit\Getlawclient\Classes\Events\OnHandleDataEvent, method: handleDbDataString, priority: 3072 }
            - { name: kernel.event_listener, event: Esit\Getlawclient\Classes\Events\OnHandleDataEvent, method: loadData, priority: 2048 }
            - { name: kernel.event_listener, event: Esit\Getlawclient\Classes\Events\OnHandleDataEvent, method: saveData, priority: 1024 }


    Esit\Getlawclient\Classes\Listener\OnLoadDataListener:
        tags:
            - { name: kernel.event_listener, event: Esit\Getlawclient\Classes\Events\OnLoadDataEvent, method: generateUrl, priority: 2048 }
            - { name: kernel.event_listener, event: Esit\Getlawclient\Classes\Events\OnLoadDataEvent, method: loadData, priority: 1024 }


    Esit\Getlawclient\Classes\Listener\OnSaveDataListener:
        tags:
            - { name: kernel.event_listener, event: Esit\Getlawclient\Classes\Events\OnSaveDataEvent, method: generateJson, priority: 2048 }
            - { name: kernel.event_listener, event: Esit\Getlawclient\Classes\Events\OnSaveDataEvent, method: saveData, priority: 1024 }


    Esit\Getlawclient\Classes\Listener\OnManualRenewListener:
        tags:
            - { name: kernel.event_listener, event: Esit\Getlawclient\Classes\Events\OnManualRenewEvent, method: loadCte, priority: 3072 }
            - { name: kernel.event_listener, event: Esit\Getlawclient\Classes\Events\OnManualRenewEvent, method: loadText, priority: 2048 }
            - { name: kernel.event_listener, event: Esit\Getlawclient\Classes\Events\OnManualRenewEvent, method: redirect, priority: 1024 }

    Esit\Getlawclient\Classes\Listener\OnHandleMessageListener:
        tags:
            - {name: kernel.event_listener, event: Esit\Getlawclient\Classes\Events\OnManualRenewEvent, method: handleKeyEmpty, priority: 8192}
            - {name: kernel.event_listener, event: Esit\Getlawclient\Classes\Events\OnManualRenewEvent, method: handleKeyTooShort, priority: 7168}
            - {name: kernel.event_listener, event: Esit\Getlawclient\Classes\Events\OnManualRenewEvent, method: handleKeyTooLong, priority: 6144}
            - {name: kernel.event_listener, event: Esit\Getlawclient\Classes\Events\OnManualRenewEvent, method: handleWrongChar, priority: 5120}
            - {name: kernel.event_listener, event: Esit\Getlawclient\Classes\Events\OnManualRenewEvent, method: handleWrongKey, priority: 4096}
            - {name: kernel.event_listener, event: Esit\Getlawclient\Classes\Events\OnManualRenewEvent, method: handleApiError, priority: 3072}
            - {name: kernel.event_listener, event: Esit\Getlawclient\Classes\Events\OnManualRenewEvent, method: setSuccessMessage, priority: 2048}
            - {name: kernel.event_listener, event: Esit\Getlawclient\Classes\Events\OnManualRenewEvent, method: setErrorMessage, priority: 1024}