services:

    # Factories
    esit_getlawclient.services.factories.http_factory:
        class: Esit\Getlawclient\Classes\Services\Factories\HttpFactory

    # Helper
    esit_getlawclient.services.helper.json_helper:
        class: Esit\Getlawclient\Classes\Services\Helper\JsonHelper
        arguments: ['@esit_getlawclient.services.helper.log_helper']
        public: true

    esit_getlawclient.services.helper.log_helper:
        class: Esit\Getlawclient\Classes\Services\Helper\LogHelper
        arguments: ['@monolog.logger.contao']


parameters:
    # getLaw-Settings
    getlaw_server_url: 'https://www.getlaw.de/api/texts/'
    getlaw_api_header: 'X-getLaw-API-Version'
    getlaw_api_version: '1'



