services:
    _defaults:
        autowire: true
        autoconfigure: true


    # Factories
    Esit\Getlawclient\Classes\Services\Factories\HttpFactory:


    # Helper
    Esit\Getlawclient\Classes\Services\Helper\ContaoHelper:

    Esit\Getlawclient\Classes\Services\Helper\JsonHelper:
        public: true

    Esit\Getlawclient\Classes\Services\Helper\LoadDataHelper:
        public: true

    Esit\Getlawclient\Classes\Services\Helper\LogHelper:

    Esit\Getlawclient\Classes\Services\Helper\MessageHelper:

    Esit\Getlawclient\Classes\Services\Helper\ScopeHelper:
        public: true

    Esit\Getlawclient\Classes\Services\Helper\TokenHelper:
        public: true
        arguments:
            - "%contao.csrf_token_name%"


    # Hooks
    Esit\Getlawclient\Classes\Contao\Hooks\RgxpHandler:
        public: true
