services:

    # Factories
    esit_getlawclient.services.factories.http_factory:
        class: Esit\Getlawclient\Classes\Services\Factories\HttpFactory

    # Helper
    esit_getlawclient.services.helper.contao_helper:
        class: Esit\Getlawclient\Classes\Services\Helper\ContaoHelper

    esit_getlawclient.services.helper.json_helper:
        class: Esit\Getlawclient\Classes\Services\Helper\JsonHelper
        arguments: ['@esit_getlawclient.services.helper.log_helper']
        public: true

    esit_getlawclient.services.helper.log_helper:
        class: Esit\Getlawclient\Classes\Services\Helper\LogHelper
        arguments: ['@monolog.logger.contao']
